name: .NET CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MYSQL_SERVER: ${{ secrets.MYSQL_SERVER }}
      MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Create Build Output Directory
      run: mkdir -p ./build-output
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        dotnet build --configuration Release --output ./build-output
    - name: Upload Build Output
      uses: actions/upload-artifact@v2
      with:
        name: build-output
        path: ./build-output
    - name: Set up SSH key
      run: |
        echo "$SSH_PRIVATE_KEY" > /tmp/id_rsa
        chmod 600 /tmp/id_rsa
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Check SSH Connection
      run: |
        ssh -o StrictHostKeyChecking=no -o BatchMode=yes -i /tmp/id_rsa -p 22 spuismys@192.168.0.105 echo "SSH connection successful"
      env:
        SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download Build Output
      uses: actions/download-artifact@v2
      with:
        name: build-output
        path: ./build-output
    - name: Check Build Output Directory
      run: |
        if [ ! -d "./build-output" ] || [ -z "$(ls -A ./build-output)" ]; then
          echo "Build output directory does not exist or is empty."
          exit 1
        fi
    - name: List Build Output
      run: ls -R ./build-output
    - name: Find Build Output
      id: find_build_output
      run: |
        # Search for the built files and output the path
        build_output=$(find ./build-output -type f -name '*.dll' -print -quit)
        echo "::set-output name=build_output_path::$build_output"
    - name: Set up SSH key
      run: |
        echo "$SSH_PRIVATE_KEY" > /tmp/id_rsa
        chmod 600 /tmp/id_rsa
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Copy files to server
      uses: appleboy/scp-action@master
      with:
        host: 192.168.0.105
        username: spuismys
        key: /tmp/id_rsa
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        source: './build-output/**/*.dll'
        target: '/var/www/html'
        debug: true
        port: 22
        timeout: 30s
        command_timeout: 10m
        use_insecure_cipher: false
        rm: false
        strip_components: 0
        overwrite: false
        tar_dereference: false
        tar_exec: tar
        proxy_port: 22
        proxy_timeout: 30s
        proxy_use_insecure_cipher: false
      env:
        SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
