name: .NET CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Create Build Output Directory
      run: mkdir -p ./build-output
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        dotnet build --configuration Release --output ./build-output
    - name: Upload Build Output
      uses: actions/upload-artifact@v2
      with:
        name: build-output
        path: ./build-output

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download Build Output
      uses: actions/download-artifact@v2
      with:
        name: build-output
        path: ./build-output
    - name: Check Build Output Directory
      run: |
        if [ ! -d "./build-output" ] || [ -z "$(ls -A ./build-output)" ]; then
          echo "Build output directory does not exist or is empty."
          exit 1
        fi
    - name: List Build Output
      run: ls -R ./build-output
    - name: Find Build Output
      id: find_build_output
      run: |
        # Search for the built files and output the path
        build_output=$(find ./build-output -type f -name '*.dll' -print -quit)
        echo "::set-output name=build_output_path::$build_output"
    - name: Copy files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: './build-output/**/*.dll'  # Adjust this path to point to your DLL files
        target: '/var/www/html'  # Adjust this path to your server's web directory
